### ISSUE TITLE
tolong ganti nama agar 'unik' dari yang lain

### ISSUE THREAD

**Issue by FONZACUS** [vim-id/vim-id#4]
<!- kurang lancar bahasa indo

salam kenal semuanya, saya ga punya HP jadi ga bisa ikutan di telegram DLL (benci sama budaya "bodohphone").

masalahnya kalo menurut saya sih banyak repo yang udah pake nama `tips`, kalo lebih menarik kaya `awesome-vim-id` itu baru unik.

**Comment by bandithijo** [comment]
> <!- kurang lancar bahasa indo
> 
> salam kenal semuanya, saya ga punya HP jadi ga bisa ikutan di telegram DLL (benci sama budaya "bodohphone").
> 
> masalahnya kalo menurut saya sih banyak repo yang udah pake nama `tips`, kalo lebih menarik kaya `awesome-vim-id` itu baru unik.

Wah!
Terima kasih sekali sudah ikut bergabung dengan kami mas.

Sebenarnya penamaan repo `tips` ini masih template saja. Saya tidak menyangka kalau akan disambut baik oleh teman-teman yang lain.

`awesome-vim-id` boleh juga, nanti coba kami diskusikan untuk pemberian nama repo yang `unik`.
Beberapa usulan nama sudah mulai bermunculan, seperti `vim-id/vim-id`.

Saya juga sudah melihat PR yang mas kirimkan.
Untuk repo yang `gg`, nanti tak coba diskusikan dengan teman-teman di group dulu yaa mas.

(^_^)

**Comment by FONZACUS** [comment]
template dasar kelompok saya kaya gini, tampilan sederhana. semua folder pasti punya README, SD, SMP dan SMA. kalo di publish ke gh-pages masih lancar. navigasi antar pages bergantungan sama folder di gh-web, kalo di pages mesti lebih diperkembang. foldernya bisa buat semua hal kaya bab, referensi dll.

saya sih kurang sanggup main jekyll pages sama git/hub. pernah berapa kali jadi min/mod di beberapa group, cuma pasti ada kesalahan. untungnya masih bisa dibenerin sama min/mod yang lain. kalo di jekyll sih aga tanggung, mending main langsung di html (sekalian bel/mengajar), cuma kan ini repo cuma buat vim ;P.

kalo mau test tinggal bikin repo baru sendiri, langsung upload semuanya. kalo masih penasaran nyalain gh-pages sekalian. udah beres hapus ;P.

[repo.zip](https://github.com/vim-id/tips/files/3563410/repo.zip)
